### ISSUE TITLE
NPC dont spawn for 2nd and 3th Banktrucks

### ISSUE THREAD

**Issue by RealMumi** [Omega248/qb-banktruck#5]
Hi I have the issue that the 2nd and 3th Robberies the trucks are empty and are not driving. I guess it has something to do with nspeedo? Because the first mission works a like charm! 

idk if I did something wrong but just put the nspeedo in my carspack...

**Comment by Omega248** [comment]
It may be because the script doesn't support one sync, unfortunately. The script is not migration aware so when the network control is migrated to another client it tends to cause sync issues and the NPCs forget the tasks that only exist on the client-side. If you are testing on a server with one sync and you are the only person on the server it should work fine. if the vans are spawning the NPCs should be spawning inside. If possible check the server and client for any errors at the time of spawning.

**Comment by RealMumi** [comment]
I'm on latest qbcore and right now its just local server and me only online ... I dont use one sync either tho and theres no errors in console thats why Im here

**Comment by Omega248** [comment]
Okay, the trucks are spawning but the guards are not?

**Comment by RealMumi** [comment]
yeah only the guards

**Comment by Omega248** [comment]
okay, are you able to spawn the vehicle with /car nspeedo?

**Comment by RealMumi** [comment]
yes but it spawns in different liveries

**Comment by Omega248** [comment]
okay that's fine I just wanted to make sure that it spawns without issue. Can you add this to line 456 in client/main.lua 
print(DoesEntityExist(BackupBack)), test the medium job and let me know if it prints true or false.

**Comment by RealMumi** [comment]
weird now it worked. I think it didnt work because I restarted the script multiple times lol 
my bad brother works like a charm

**Comment by Omega248** [comment]
no problem, if you get any more issues feel free to create a new issue.
